### ISSUE TITLE
Changing license text

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [awjh/license-check-and-add#1]
Hi, first of thanks for the great lib!

Is there a plan to update license text in case they change over time? It can be small changes (i.e.. calendar year) or larger changes. As this is not a regular thing, I can imagine you could support a clean method, that removes the license for all files that contain the license. You probably can reuse most of your logic, and do not introduce complicated configurations (such as v1 vs v2 license text).

**Comment by awjh** [comment]
Hey, thanks for raising the issue, I hadn't though about use cases like that but you're right it would be a handy method to have in. I will try and get this in at some point in the future :+1:

**Comment by tobi-or-not-tobi** [comment]
Thanks a lot for the prompt reply 👍

**Comment by awjh** [comment]
V2.2.0 should now implement this feature.
