### ISSUE TITLE
Cannot handle file name which starts with dot

### ISSUE THREAD

**Issue by cutePanda123** [awjh/license-check-and-add#11]
Thanks for the work on this library. I am running into a bug today, the checker cannot handle file which starts with '.', for example, .gitignore and .npmrc. After a look at the source code, I found the root cause. In index.js, it uses path.extname to extract the file format. If filename starts with a dot, the extracting result will be empty.

**Comment by awjh** [comment]
Hi, are you able to tell me which version you are running? I have just tried this on a repository I use this package on and can confirm that it is checking the licenses of file beginning with a dot (I tried with an npmrc file)

**Comment by awjh** [comment]
Closed as unable to replicate
