### ISSUE TITLE
Feature suggestion: Enable "check" to accept a pattern

### ISSUE THREAD

**Issue by dbjorge** [awjh/license-check-and-add#15]
It would be nice to be able to separate the notions of "the default license text to be added for a new file" vs "the pattern of acceptable license text to be checked against". For example, I work on several projects where the overwhelming majority of contributions are copyright Microsoft, but we want to allow for contributions by 3rd parties that might need a different copyright header, so our team would love to be able to write something along the lines of:

```json
license: "Copyright (c) Microsoft Corporation.\nLicensed under the MIT License.",
licenseCheckRegex: "Copyright \\(c\\) (?<file_contributors>[^\\n]+)\\.\\nLicensed under the MIT License\\."
```

So far, we've just been adding files with unique copyright statements to the ignore list - this works okay for us because there aren't *that* many exceptional cases in practice, but it'd be nicer to be able to express the pattern and prevent regressions in those files.

Probably it would be ideal for the checker to treat a license property that doesn't adhere to the license pattern property as an error.

**Comment by awjh** [comment]
Added ability to use a license containing regex patterns in v4.0.0 through the introduction of regexIdentifier option. Can also insert into files with a specified replacement

**Comment by dbjorge** [comment]
Awesome, thank you very much!
