### ISSUE TITLE
[3.x regression] check always fails for files with line endings that differ from os.EOL

### ISSUE THREAD

**Issue by dbjorge** [awjh/license-check-and-add#16]
In 2.3.6, the checker was agnostic to line endings (in that it split file contents by line and then rejoined them normalized them as `\n` before performing the license check, see [index.js@v2.3.6 L173](https://github.com/awjh/license-check-and-add/blob/d02552be0ad5a0cdaf69e7d5c75c8b7962848fcf/index.js#L173]).

In 3.0.1, the checker no longer performs this normalization, so any case where `os.EOL` differs from files in the repository (ie, any user on windows working with autocrlf=false) will cause the checker to reject every file where the license would contain newlines.

**Comment by awjh** [comment]
Thanks for the heads up. #17 fixes this

**Comment by awjh** [comment]
Release fix - 3.0.2

**Comment by dbjorge** [comment]
Verified that 3.0.2 fixes our usage of the checker, thanks for the quick response!
