### ISSUE TITLE
Using prepend for each line with empty content is causing lint conflicts

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [awjh/license-check-and-add#2]
When we use the following configuration snippet for adding a license:

```
"license_formats": {
    "js|ts": {
        "prepend": "/*",
        "append": " */",
        "eachLine": {
            "prepend": " * "
        }
    }
}
```

The generated output is not valid for our lint rules. This is caused by a combination of a blank line in our license text and the prepend " * " given for each line. This conflict with the no-trailing-whitespace lint rule. 

> [tslint] trailing whitespace (no-trailing-whitespace)

Would it be possible to add a configuration for this scenario?

**Comment by tobi-or-not-tobi** [comment]
We've tried to be created as a workaround: remove the trailing space and add a space before each line (except the blank lines) in our license text. That was promising, but doesn't work on the first line, most probably because you're trimming the incoming license text. The trimming part is fine, but blocks our workaround.

**Comment by awjh** [comment]
v2.3.2 should now contain an option for removing trailing whitespace. Setting trailing_whitespace to 'TRIM' in your package.json should invoke this

**Comment by awjh** [comment]
Please let me know if this solution works for you and close here if it does

**Comment by tobi-or-not-tobi** [comment]
Trimming of the line is actually causing the issue that also the intended spaces before the line are being trimmed. The format:

```
/*
 * MyCompany
 *
 * Copyright (c) 2018MyCompany. All rights reserved.
 */
```

Is turned into: 

```
/*
* MyCompany
*
* Copyright (c) 2018MyCompany. All rights reserved.
*/
```

That's a very subtle difference, but the spaces before the star are being trimmed. Since this is targeting the trailing_whitespace, it would be nice to optimise the code and only trim the last trailing space.

**Comment by tobi-or-not-tobi** [comment]
Thanks for your quick response here btw, appreciated!

**Comment by tobi-or-not-tobi** [comment]
Works really well, thanks!
