### ISSUE TITLE
Should ignore .git folder by default

### ISSUE THREAD

**Issue by awjh-ibm** [awjh/license-check-and-add#21]
The git folder is used to store information about the git repository and as such it is unlikely that it should be checked for files with matching license

**Comment by dod38fr** [comment]
I mistakenly ran the "add" command with default setup. As a consequence, my local .git repo was a mess. 

I think `license-check-and-add` should *never* modify files in `.git` directory

**Comment by awjh** [comment]
Ignored by default in v4.0.0
