### ISSUE TITLE
As a user I should be able to combine my gitignore and other ignores

### ISSUE THREAD

**Issue by awjh-ibm** [awjh/license-check-and-add#22]
Currently as a user I have to ignore things twice, once in my gitignore to ensure they don't go to github and once for the license checker. This may be negated by running the license checker when certain files aren't present on a CI such as travis but often as tests are run on local mahcines prior to being pushed the folders that are gitignored are also ignored by the tests.

It would therefore be preferable if I could have the option to append extra ignore rules to my preexisting rules from my ignore file.

**Comment by awjh** [comment]
Introduced ignoreFile option in v4.0.0 that works with ignore array
