### ISSUE TITLE
Add ignoreFiles option.

### ISSUE THREAD

**Issue by 10ko** [awjh/license-check-and-add#28]
The current `ignore` field accepts 

> **Either** the path to an ignore style file (e.g. gitignore) or an array of globby strings specifying which files to ignore (e.g. ["**/*.txt"]).

It would be nice to make the `ignore` field only accept "an ignore style file" and add an additional field `ignoreFiles` to list the globs of paths we want to exclude.

The reasoning behind this I often find myself wanting to exclude files in the .gitignore files togheter with other files which are versioned but don't need a license (and don't fall into the category of  default extensions/paths). With the current capabilities I end up duplicating my .gitignore files within `ignore` and adding few more files/globs.

Is this something that anyone else would find useful?
I could try to conjure a PR when I have time.

Emanuele.

**Comment by awjh** [comment]
Included in v4.0.0

**Comment by 10ko** [comment]
Awesome, thanks!
