### ISSUE TITLE
Clear command throws errors

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [awjh/license-check-and-add#3]
Whenever the clear command comes across files that do not have a license being added, it fails. This is not needed, as we might have only a few files that have licenses, and we just want clear things. Also, it avoids to run this command twice (i.e. in CI). 

A warning could be fine, but event that is no needed from my pov. 

Anyway, thanks for adding this feature!

**Comment by awjh** [comment]
v2.3.4 should contain the fix for this
