### ISSUE TITLE
A leading whitespace in a license file causes all subsequent lines to be incremented by that amount of white space

### ISSUE THREAD

**Issue by DJodeit** [awjh/license-check-and-add#31]
Given the license file with the following:

```
ATTENTION: This is a header Statement
           This line should follow right under

Distribution Statement 626:
           The word distribution should line up under ATTENTION
           This line should line up with above
```
I expect to see:
```
/*
 * ATTENTION: This is a header Statement
 *            This line should follow right under
 *
 * Distribution Statement 626:
 *            The word distribution should line up under ATTENTION
 *            This line should line up with above
 */
```
However, if the license file has spaces in front of the first line like this (2 spaces in this example)
```
  ATTENTION: This is a header Statement
             This line should follow right under

  Distribution Statement 626:
             The word distribution should line up under ATTENTION
             This line should line up with above
```
You get the following header inserted into the file:

```
/*
 * ATTENTION: This is a header Statement
 *              This line should follow right under
 *
 *   Distribution Statement 626:
 *              The word distribution should line up under ATTENTION
 *              This line should line up with above
 */
```
You can see that each line after "ATTENTION..." has two extra spaces in front of it

**Comment by awjh** [comment]
Hello, thanks for raising this issue. Having looked at the code this is due to a trim being performed on the license text as a whole meaning that the whitespace at the start of the first line is being removed.

What is the reasoning behind why the license text would have spaces at the very start? Could the goal formatting be achieved by using the licenseFormats option to add the additional space?

**Comment by DJodeit** [comment]
I see in the code where the trim is performed. I attempted to use the licenseFormat options to account for the leading spaces but couldn't get that to work as anticipated.

Since each line in the license file has the option to trim trailing spaces is there still a need to trim the entire license file to remove any leading space?

The license file was provided to me but I think the best course of action for me is to work through the process to remove the leading spaces.

**Comment by awjh** [comment]
I think the intent behind the trim was to remove any blank lines before and after the license and it was a lazy trim. I think I will go in and change the trim to a replace

**Comment by awjh** [comment]
In the mean time you should be able to remove any leading whitespace on each line and update the licenseFormatOptions to each line add a `*   `
