### ISSUE TITLE
Leading whitespaces are ignored during license check

### ISSUE THREAD

**Issue by hcsalis** [awjh/license-check-and-add#5]
Hi @awjh,

Thank you for your work on this library. I came across this bug today and went through the source to find the root cause. It looks like the library compares trimmed versions of files and the license, but this causes license header 2 below to pass the checks:

license.txt
```
license
```
config
```json
{
  "prepend": "/*",
  "append": " */",
  "eachLine": {
    "prepend": " * "
  }
}
```

Header 1: Passes check:
```js
/*
 * license
 */
```
Header 2: Shouldn't pass the check, but it does:
```js
/*
* license
*/
```

If is this not a bug but an intended behaviour, would you consider adding an option to opt-out of this behaviour?

Cheers

**Comment by awjh** [comment]
This is a bug and both sides are trimmed, the solution I am looking into will involve no longer trimming the starting whitespace of the file being checked but still trimming the trailing whitespace if and only if the TRAILING_WHITESPACE option in the config is not set to TRIM. If it is set to trim then the file will be checked as is against the formatted license.

**Comment by awjh** [comment]
v2.3.5 address this issue
